# Generated by Django 5.2.1 on 2026-01-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Soporte', 'Soporte'), ('Infra', 'Infraestructura'), ('BD', 'Base de Datos'), ('Seguridad', 'Seguridad')], max_length=50)),
                ('color', models.CharField(default='#3788d8', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.especialista')),
            ],
            options={
                'unique_together': {('especialista', 'fecha')},
            },
        ),
    ]
